export const ERROR_CODE = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  REQUIRED_FIELD_MISSING: 'REQUIRED_FIELD_MISSING',
  INVALID_STATUS: 'INVALID_STATUS',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  UNSUPPORTED_FILE_FORMAT: 'UNSUPPORTED_FILE_FORMAT',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  APPLICATION_NOT_FOUND: 'APPLICATION_NOT_FOUND',
  SUBMISSION_FILE_NOT_FOUND: 'SUBMISSION_FILE_NOT_FOUND',
  APPLICATION_FILE_LINK_NOT_FOUND: 'APPLICATION_FILE_LINK_NOT_FOUND',
  SUBMISSION_FILE_ALREADY_LINKED: 'SUBMISSION_FILE_ALREADY_LINKED',
  SUBMISSION_FILE_IN_USE: 'SUBMISSION_FILE_IN_USE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
